import { database } from '@/db/raw';
import { seedTasks } from '@/lib/tasks';
import { z } from 'zod';
const linkSchema=z.object({label:z.string().trim().max(200),url:z.string().trim().max(2000).url().refine(u=>/^https?:\/\//i.test(u))});
const linkList=z.array(linkSchema).max(20).optional();
function parseLinks(v:unknown){try{const a=JSON.parse(String(v??'[]'));return Array.isArray(a)?a:[];}catch{return [];}}
const taskSchema=z.object({id:z.string().min(1).max(100),title:z.string().trim().min(1).max(160),notes:z.string().max(2000),q:z.number().int().min(0).max(3),x:z.number().finite().min(0).max(1760),y:z.number().finite().min(0).max(1460),done:z.boolean(),due:z.string().refine(v=>!v||/^\d{4}-\d{2}-\d{2}$/.test(v)),sources:linkList,links:linkList});
function failure(e:unknown){console.error('Board operation failed',e);return Response.json({error:'Board storage is temporarily unavailable. Please try again.'},{status:503});}
export async function GET(){try{const db=database();const initialized=await db.prepare('SELECT id FROM board_meta WHERE id = ?').bind('initial').first();if(!initialized){await db.batch([...seedTasks.map(t=>db.prepare('INSERT OR IGNORE INTO tasks (id,title,notes,q,x,y,done,due) SELECT ?,?,?,?,?,?,?,? WHERE NOT EXISTS (SELECT 1 FROM board_meta WHERE id = ?)').bind(t.id,t.title,t.notes,t.q,t.x,t.y,0,t.due,'initial')),db.prepare('INSERT OR IGNORE INTO board_meta (id) VALUES (?)').bind('initial')]);}const rows=await db.prepare('SELECT * FROM tasks ORDER BY id').all();return Response.json({tasks:rows.results.map(r=>({...r,done:!!r.done,sources:parseLinks(r.sources),links:parseLinks(r.links)}))},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function PUT(request:Request){try{if(!request.headers.get('content-type')?.includes('application/json'))return Response.json({error:'JSON required'},{status:415});const parsed=taskSchema.safeParse(await request.json());if(!parsed.success)return Response.json({error:'Invalid task'},{status:400});const t=parsed.data;await database().prepare('INSERT INTO tasks (id,title,notes,q,x,y,done,due,sources,links) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,COALESCE(?9,\'[]\'),COALESCE(?10,\'[]\')) ON CONFLICT(id) DO UPDATE SET title=excluded.title,notes=excluded.notes,q=excluded.q,x=excluded.x,y=excluded.y,done=excluded.done,due=excluded.due,sources=COALESCE(?9,tasks.sources),links=COALESCE(?10,tasks.links)').bind(t.id,t.title,t.notes,t.q,t.x,t.y,Number(t.done),t.due,t.sources?JSON.stringify(t.sources):null,t.links?JSON.stringify(t.links):null).run();return Response.json({ok:true});}catch(e){if(e instanceof SyntaxError)return Response.json({error:'Invalid JSON'},{status:400});return failure(e);}}
export async function DELETE(request:Request){try{if(!request.headers.get('content-type')?.includes('application/json'))return Response.json({error:'JSON required'},{status:415});const parsed=z.object({id:z.string().min(1).max(100)}).safeParse(await request.json());if(!parsed.success)return Response.json({error:'Invalid task'},{status:400});await database().prepare('DELETE FROM tasks WHERE id = ?').bind(parsed.data.id).run();return Response.json({ok:true});}catch(e){if(e instanceof SyntaxError)return Response.json({error:'Invalid JSON'},{status:400});return failure(e);}}
